name: Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build main project
        run: cargo build --release

      - name: Build and test examples
        run: |
          cargo build --examples

      - name: Run tests
        run: cargo test
